### ISSUE TITLE
Incompatibility with MTG

### ISSUE THREAD

**Issue by appgurueu** [rollerozxa/minetest-enable-shadows#1]
This mod claims "compatibility with all games" but appears to be [incompatible with MTG](https://github.com/minetest/minetest_game/pull/2938)

**Comment by lhofhansl** [comment]
I think it was more meant as "This mod has no dependencies". Any mod that also sets the shadow density (such as the weather mod in MTG) will naturally clash with this.

**Comment by rollerozxa** [comment]
Yeah I'm inclined to say that this mod is supposed to only be used for games that right now do not implement their own code to control shadows (which would be all games except for MTG and NodeCore). I probably should rephrase the description to reflect this.
