### ISSUE TITLE
Godrays

### ISSUE THREAD

**Issue by tenplus1** [rollerozxa/minetest-enable-shadows#2]
Could you add the ability to enable and control volumetric lighting in the next update :)

**Comment by rollerozxa** [comment]
Hi, I made a separate mod during 5.9.0-dev for controlling the volumetric lighting: [Volumetric Lighting](https://content.minetest.net/packages/ROllerozxa/volumetric_lighting/). It might have been a better idea to put all the effects into a single mod as they gradually add more graphical effects and knobs to control them, but we'll see.
